<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.13" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1001" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdminMasters\AdminMasters.csproj" />
    <ProjectReference Include="..\Consignment\Consignment.csproj" />
    <ProjectReference Include="..\FinanceMaster\FinanceMaster.csproj" />
    <ProjectReference Include="..\FinTrans\FinTrans.csproj" />
    <ProjectReference Include="..\FleetMasters\FleetMasters.csproj" />
    <ProjectReference Include="..\FleetTrans\FleetTrans.csproj" />
    <ProjectReference Include="..\FreightMasters\FreightMasters.csproj" />
    <ProjectReference Include="..\HRMasters\HRMasters.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="reports\ExpTruckArrRPT\" />
    <Folder Include="upload\docrenewal\attach1\" />
    <Folder Include="upload\docrenewal\attach2\" />
    <Folder Include="upload\driver\driverphoto\" />
    <Folder Include="upload\driver\drivinglicense\" />
    <Folder Include="upload\driver\hazdrivinglicense\" />
    <Folder Include="upload\driver\aadharcard\" />
    <Folder Include="upload\driver\bankpassbook\" />
    <Folder Include="upload\driver\" />
    <Folder Include="upload\driver\peraddressprove\" />
    <Folder Include="upload\driver\tempaddressprove\" />
    <Folder Include="upload\gstpurchase\attatchFile1\" />
    <Folder Include="upload\gstpurchase\attatchFile2\" />
    <Folder Include="upload\user\userphoto\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Office.Interop.Excel">
      <HintPath>..\..\..\..\Suni_Proj\Microsoft.Office.Interop.Excel.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
