
namespace Consignment.Models
{
    public class ConsignmentModel
    {   
        public string? ConsignmentID            { get; set; }
        public string? BookingPlace             { get; set; }
        public string? BookedAt                 { get; set; }
        public string? GcNoteNo                 { get; set; }
        public string? BookingDate              { get; set; }
        public string? BookingStatus            { get; set; }
        public string? EwayBillEntryType        { get; set; }
        public string? EwayBillNo               { get; set; }
        public string? EwayBillDate             { get; set; }
        public string? EwayBillExpDate          { get; set; }
        public string? InvoiceNo                { get; set; }
        public string? InvoiceDate              { get; set; }
        public string? InvoiceValue             { get; set; }
        public string? DeclaredValue            { get; set; }
        public string? FromPlace                { get; set; }
        public string? ToPlace                  { get; set; }
        public string? FPlace                   { get; set; }
        public string? TPlace                   { get; set; }
        public string? Kms                      { get; set; }
        public string? OwnTruck                 { get; set; }
        public string? TruckNo                  { get; set; }
        public string? BillingParty             { get; set; }
        public string? BillingBranch            { get; set; }
        public string? BusinessBranch           { get; set; }
        public string? CnorName                 { get; set; }
        public string? CnorAdd1                 { get; set; }
        public string? CnorAdd2                 { get; set; }
        public string? CnorAdd3                 { get; set; }
        public string? CnorPin                  { get; set; }
        public string? CnorGst                  { get; set; }
        public string? CnorMobile               { get; set; }
        public string? CnorEmail                { get; set; }
        public string? CneeName                 { get; set; }
        public string? CneeAdd1                 { get; set; }
        public string? CneeAdd2                 { get; set; }
        public string? CneeAdd3                 { get; set; }
        public string? CneePin                  { get; set; }
        public string? CneeGst                  { get; set; }
        public string? CneeMobile               { get; set; }
        public string? CneeEmail                { get; set; }
        public string? ShipmentNo               { get; set; }
        public string? ShipmentDt               { get; set; }
        public string? DeliveryNo               { get; set; }
        public string? DeliveryDt               { get; set; }
        public string? PoNo                     { get; set; }
        public string? PoDt                     { get; set; }
        public string? RiskBy                   { get; set; }
        public string? InsCoName                { get; set; }
        public string? InsPolicyNo              { get; set; }
        public string? InsValidDt               { get; set; }
        public string? InsuredValue             { get; set; }
        public string? ClassId                  { get; set; }
        public string? ProductId                { get; set; }
        public string? ProductDesc              { get; set; }
        public string? HsnSac                   { get; set; }
        public string? NoPackages               { get; set; }
        public string? LooseFlag                { get; set; }
        public string? WeightType               { get; set; }
        public string? ActualWt                 { get; set; }
        public string? SenderWt                 { get; set; }
        public string? Chargewt                 { get; set; }
        public string? WtDesc                   { get; set; }
        public string? VehicleTypeId            { get; set; }
        public string? PrivateMark              { get; set; }
        public string? BulkYN                   { get; set; }
        public string? LoadLength               { get; set; }
        public string? LoadWidth                { get; set; }
        public string? LoadHeight               { get; set; }
        public string? LoadCFT                  { get; set; }
        public string? RateType                 { get; set; }
        public string? RateDesc                 { get; set; }
        public string? GstBy                    { get; set; }
        public string? RateRs                   { get; set; }
        public string? FreightRs                { get; set; }
        public string? StatisticalRs            { get; set; }
        public string? FovRs                    { get; set; }
        public string? DoorCollRs               { get; set; }
        public string? HandlingRs               { get; set; }
        public string? LoadingDetnRs            { get; set; }
        public string? EnrouteRs                { get; set; }
        public string? MiscRs                   { get; set; }
        public string? DoorDelRs                { get; set; }
        public string? UnLoadingRs              { get; set; }
        public string? UnLoadingDetnRs          { get; set; }
        public string? ExtrasRS                 { get; set; }
        public string? OthersRs                 { get; set; }
        public string? SubTotalRs               { get; set; }
        public string? GstType                  { get; set; }
        public string? SgstPct                  { get; set; }
        public string? SgstAmt                  { get; set; }
        public string? CgstPct                  { get; set; }
        public string? CgstAmt                  { get; set; }
        public string? IgstPct                  { get; set; }
        public string? IgstAmt                  { get; set; }
        public string? NonGstAmt1               { get; set; }
        public string? NonGstAmt1Desc           { get; set; }
        public string? NonGstAmt2               { get; set; }
        public string? NonGstAmt2Desc           { get; set; }
        public string? GtotalRs                 { get; set; }
        public string? AdvanceRs                { get; set; }
        public string? AmountRecd               { get; set; }
        public string? TdsDeducted              { get; set; }
        public string? Deduction1               { get; set; }
        public string? Deduction2               { get; set; }
        public string? Deduction3               { get; set; }
        public string? ExtrasRecd1              { get; set; }
        public string? ExtrasRecd2              { get; set; }
        public string? DeliveredYN              { get; set; }
        public string? LdReportingDateTime      { get; set; }
        public string? DespatchDateTime         { get; set; }
        public string? LdDetentionDays          { get; set; }
        public string? UlReportingDateTime      { get; set; }
        public string? DeliveryDateTime         { get; set; }
        public string? UlDetentionDays          { get; set; }
        public string? PodRecdYN                { get; set; }
        public string? GeneralRemarks           { get; set; }
        public string? CnBilledYN               { get; set; }
        public string? CnBillDate               { get; set; }
        public string? IncludeCnYn              { get; set; }
        public string? IncludeCnNo              { get; set; }
        public string? BusinessBy               { get; set; }
        public string? Attachedfile             { get; set; }
        public string? YearId                   { get; set; }
        public string? LoggedInUser             { get; set; }
        public List<ConsignmentInvModel> InvList { get; set; }


    }
}
