import { Tripsheetinnergridmodel } from "./tripsheetinnergridmodel";

export class Tripsheetmodel {
    tripId: string = "";
    tripBranch: string = "";
    yearId: string = "";
    vehicleMasterID: string = "";
    tripNo: string = "";
    lastTripCloseDate: string = "";
    newTripDate: string = "";
    openThrough: string = "";
    tripOpenBy: string = "";
    tripOpenDate: string = "";
    tripStatus: string = "";
    driverMasterID: string = "";
    consignorPayParty: string = "";
    compNonCompStatus: string = "";
    challanNo: string = "";
    loadingFrom: string = "";
    destination: string = "";
    destination2: string = "";
    destination3: string = "";
    distanceTripKM_1: string = "";
    contents: string = "";
    loadEmptyType: string = "";
    expectedReportingDt: string = "";
    expectedReportingDays: string = "";
    ltsDslToBe_1: string = "";
    ltsAdblueToBe_1: string = "";
    advPayable_1: string = "";
    reportingDt_1: string = "";
    advanceDays_1: string = "";
    delayedDays_1: string = "";
    graceDays_1: string = "";
    deliveryDate: string = "";
    detentionDays: string = "";
    nextReportingBranch: string = "";
    distanceTripKM_2: string = "";
    nextExpectedReportingDt: string = "";
    nextExpectedReportingDays: string = "";
    ltsDslToBe_2: string = "";
    ltsAdblueToBe_2: string = "";
    advPayable_2: string = "";
    reportingDt_2: string = "";
    advanceDays_2: string = "";
    delayedDays_2: string = "";
    graceDays_2: string = "";
    opBalDriver: string = "";
    opBalDsl: string = "";
    opBalAdblue: string = "";
    paidDriverAdvance: string = "";
    freightCollByDriver: string = "";
    issuedDslLtrs: string = "";
    issuedAdblueLtrs: string = "";
    repairsByDriver: string = "";
    challanByDriver: string = "";
    parkingByDriver: string = "";
    accidentByDriver: string = "";
    weighmentByDriver: string = "";
    otherExpByDriver: string = "";
    tollExpByDriver: string = "";
    cashDslPlace: string = "";
    cashDslLtrs: string = "";
    cashDslAmt: string = "";
    totalBhattaDays: string = "";
    bhattaRate: string = "";
    allowedBhatta: string = "";
    onTimeIncentiveAmt: string = "";
    multiDelIncentiveAmt: string = "";
    penaltyChargedToDr: string = "";
    poolAcAmt: string = "";
    totalDriverAc: string = "";
    tripBalance: string = "";
    recdFromDriver: string = "";
    netTripBalance: string = "";
    clBalDsl: string = "";
    clBalAdBlue: string = "";
    ticlStatus: string = "";
    ticlRemarks: string = "";
    tripCloseBy: string = "";
    tripCloseDt: string = "";
    tripCloseUpdateDt: string = "";
    tripLinkYN: string = "";
    tripSalDoneYN: string = "";
    findocid: string = "";
    tripBrName: string = "";
    vehicleNo: string = "";
    drName: string = "";
    frPlace: string = "";
    tPlace: string = "";
    loggedInUser: string = "";

    tripSheetInnerGridList: Tripsheetinnergridmodel = new Tripsheetinnergridmodel();
    miscList: MiscListmodel[] = [];
    adblueList: AdblueListmodel[] = [];
}

export class MiscListmodel {
    expType: string = "";
    miscAmount: string = "";
    narration: string = "";
}

export class AdblueListmodel {
    adbluefillingStation: string = "";
    adbluedieselLiter: string = "";
    adbluedieselAmount: string = "";
}