export class Mrdtlsmodel {
    mrMasterId : string = ""
    mrStation: string = ""
    mrNo : string = ""
    mrDate: string = ""
    partyCode : string = ""
    billLrYear : string = ""
    billLrStn: string = ""
    billLrNo : string = ""
    billLrDate : string = ""
    billLrMasterId : string = ""
    dueAmt : string = ""
    oldDueAmt: string = ""
    recdAmt : string = ""
    freightDed : string = ""
    claimsDed: string = ""
    othersDed: string = ""
    bankChrgDed : string = ""
    othersDed1 : string = ""
    othersDed2 : string = ""
    othersDed3 : string = ""
    recoverable : string = ""
    totDed : string = ""
    tdsDed : string = ""
    sdEmdDed : string = ""
    excessRecd : string = ""
    others1Recd : string = ""
    others2Recd : string = ""
    remarks : string = ""
    yearId : string = ""
        
}
