export class Dashboardmodel {
    totalBusi : string = ""
    preMonth : string = ""
    prvMonth : string = ""
    oldMonth : string = ""    
    preMonName : string = ""
    prvMonName : string = ""
    oldMonName : string = ""
    totBilledCnt : string = ""
    totBilledAmt : string = ""
    totUnBilledCnt : string = ""
    totUnBilledAmt : string = ""
    billedCnt : string = ""
    billedAmt : string = ""
    unBilledCnt : string = ""
    unBilledAmt : string = ""
    pendingAckCnt : string = ""
    pendingAckAmt : string = ""
    vehiCnt : string = ""
}
