export class Documentallotmentmodel {
    docAllotId: string = "";
    branchCode: string = "";
    branch: string = "";
    docType: string = "";
    docNumCode: string = "";
    allotDate: string = "";
    rangeFrom: string = "";
    rangeTo: string = "";
    docCount: string = "";
    docStatus: string = "";
    docCloseDate: string = "";
    docUsedCount: string = "";
    docMaxNo: string = "";
    autoGenYN: string = "";
    remarks: string = "";
    seriesCode: string = "";
    loggedInUser: string = "";
}
