export class Dovehiplacedmodel {
    doId : string = ""
    doBranch : string = ""        
    doNo : string = ""
    doDate : string = ""
    partyDoNo : string = ""
    doQty : string = ""
    doRemarks : string = ""        
    doQtyLift : string = ""
    loadingFr : string = ""
    dest : string = ""
    partyName : string = ""
    cnorName : string = ""
    cneeName : string = ""
    doVpId : string = ""
    placementDate : string = ""
    vehicleNo : string = ""
    vehicleType : string = ""
    ownMarket : string = ""
    brokerId : string = ""
    hireRateType : string = ""
    hireRate : string = ""
    hireAmt : string = ""
    vehicleEngBy : string = ""
    loadAssignTo : string = ""
    placementRem : string = ""
    lrDoneYN : string = ""
    lrBranch : string = ""
    lrNo : string = ""
    loggedInUserID : string = ""
    createdBy : string = ""
    createdDate : string = ""
    modifiedBy : string = ""
    modifiedDate : string = ""

}


