import { Dprdtlsmodel } from "./dprdtlsmodel";

export class Dprmodel {
    dprId : string = "";             
    dprBranch : string = "";         
    dprSlNo  : string = "";          
    dprDate  : string = "";          
    payParty  : string = "";         
    partyName    : string = "";      
    bookStatus  : string = "";       
    origin   : string = "";          
    fromPlace   : string = "";       
    destination  : string = "";      
    toPlace     : string = "";       
    vehicleTypeId : string = ""; 
    vehTypeDesc : string = "";   
    actualWt  : string = "";         
    chargeWt  : string = "";         
    odcDimensions   : string = "";   
    odcCft : string = "";            
    rateType  : string = "";         
    rateRs   : string = "";          
    freightRs : string = "";         
    hamaliAmt : string = "";         
    hamaliDesc   : string = "";      
    ldDetenAmt  : string = "";       
    ldDetenDesc : string = "";       
    extraAmt: string = "";           
    extraDesc   : string = "";       
    otherAmt   : string = "";        
    otherDesc  : string = "";        
    totFreightAmt   : string = "";   
    attachConfirmDoc : string = "";  
    dPR_Status  : string = "";       
    vehicleNo  : string = "";  
    brokerName   : string = "";    
    driverName  : string = "";       
    driverMob   : string = "";     
    noofLr  : string = "";    
    businessBy: string = "";    
    loggedInUserID: string = "";
    createdBy: string = "";
    createdDate: string = "";
    modifiedBy: string = "";
    modifiedDate: string = "";
    dprDtls: Dprdtlsmodel[] = [];
}
