import { Mrdtlsmodel  } from './mrdtlsmodel';
import { Mronacmodel  } from './mronacmodel';

export class Mrmodel {
    mrMasterId : string = ""
    mrStation : string = ""
    mrStn : string = ""
    mrNo : string = ""
    mrDate : string = ""
    mrStatus : string = ""
    mrReceiptType : string = ""
    mrType : string = ""
    billLrOthType : string = ""
    groupMrYN : string = ""
    partyGroupId : string = "" 
    partyCode : string = ""
    partyName : string = ""
    cheqCashAmt : string = ""
    onAcAdjAmt : string = ""
    totalAmt : string = ""
    onAcNewAmt : string = ""
    onAcAdjusted : string = "" 
    onAcStatus : string = ""
    onAcAdjMrYn : string = ""
    totalRecdAmt : string = "" 
    totalFreightDed : string = ""
    totalClaimsDed : string = ""
    totalOldFrtDed : string = ""
    totalOldClaims : string = ""
    totalOthersDed : string = ""
    totalBankChrgDed : string = ""
    totalOthersDed1 : string = ""
    totalOthersDed2 : string = ""
    totalOthersDed3 : string = ""
    totalRecoverable : string = ""
    totalDed : string = ""
    totalTDSDed : string = ""
    totalSdEmdDed : string = ""
    totalExcess : string = ""
    totalOthers1 : string = "" 
    totalOthers2 : string = "" 
    mrRemarks : string = ""
    crAdviceNo : string = ""
    chequeReturn : string = "" 
    chequeReturnDt : string = ""
    chequeReturnRemarks : string = ""
    ftmid : string = ""
    ftmidJv : string = ""
    neftYN : string = ""
    mrDebitAc : string = ""
    mrSdEmdAc : string = ""
    sdEmdRefNo : string = ""
    partyBankDet : string = "" 
    chequeNo : string = ""
    chequeDt : string = ""
    modifyRemarks : string = ""
    yearId : string = ""
    loggedInUser : string = "" 

    
    mrDtlsList: Mrdtlsmodel[] = [];
    mrOnAcList: Mronacmodel[] = [];
        
}
